In [68]:
import xarray as xr
import numpy as np

dss = xr.open_dataset('/data/ycheng/JRA/Data/1958/sst_19581231.nc',engine='netcdf4')



In [69]:
lonres = dss['longitude'][1]-dss['longitude'][0]

In [70]:
print(lonres)

<xarray.DataArray 'longitude' ()>
array(1.25)
Coordinates:
    number   int64 0
    step     timedelta64[ns] 03:00:00
    surface  float64 0.0


In [67]:
if any(dss['longitude'] < 0 ):
    print('shifting longitude to postive only values')
    dss['longitude'] = np.linspace(0, 360, dss['longitude'].shape[0], endpoint=False)
print(dss['longitude'])

shifting longitude to postive only values
<xarray.DataArray 'longitude' (longitude: 288)>
array([  0.  ,   1.25,   2.5 , ..., 356.25, 357.5 , 358.75])
Coordinates:
    number     int64 ...
    step       timedelta64[ns] ...
    surface    float64 ...
  * longitude  (longitude) float64 0.0 1.25 2.5 3.75 ... 355.0 356.2 357.5 358.8


In [60]:
ds = xr.open_dataset('/data/ycheng/JRA/Data/1958/fcst_surf125.118_brtmp.1958010100_1958123121',engine='cfgrib')

In [61]:
ds

<xarray.Dataset>
Dimensions:     (time: 1461, step: 2, latitude: 145, longitude: 288)
Coordinates:
    number      int64 ...
  * time        (time) datetime64[ns] 1957-12-31T18:00:00 ... 1958-12-31T18:0...
  * step        (step) timedelta64[ns] 03:00:00 06:00:00
    surface     float64 ...
  * latitude    (latitude) float64 90.0 88.75 87.5 86.25 ... -87.5 -88.75 -90.0
  * longitude   (longitude) float64 -1.25 0.0 1.25 2.5 ... 355.0 356.2 357.5
    valid_time  (time, step) datetime64[ns] ...
Data variables:
    btmp        (time, step, latitude, longitude) float32 ...
Attributes:
    GRIB_edition:            1
    GRIB_centre:             rjtd
    GRIB_centreDescription:  Japanese Meteorological Agency - Tokyo
    GRIB_subCentre:          241
    Conventions:             CF-1.7
    institution:             Japanese Meteorological Agency - Tokyo
    history:                 2023-06-01T22:20 GRIB to CDM+CF via cfgrib-0.9.1...

In [64]:
print(ds['btmp'][0])

<xarray.DataArray 'btmp' (step: 2, latitude: 145, longitude: 288)>
[83520 values with dtype=float32]
Coordinates:
    number      int64 ...
    time        datetime64[ns] 1957-12-31T18:00:00
  * step        (step) timedelta64[ns] 03:00:00 06:00:00
    surface     float64 ...
  * latitude    (latitude) float64 90.0 88.75 87.5 86.25 ... -87.5 -88.75 -90.0
  * longitude   (longitude) float64 -1.25 0.0 1.25 2.5 ... 355.0 356.2 357.5
    valid_time  (step) datetime64[ns] ...
Attributes: (12/30)
    GRIB_paramId:                             194
    GRIB_dataType:                            0
    GRIB_numberOfPoints:                      41760
    GRIB_typeOfLevel:                         surface
    GRIB_stepUnits:                           1
    GRIB_stepType:                            instant
    ...                                       ...
    GRIB_shortName:                           btmp
    GRIB_totalNumber:                         0
    GRIB_units:                               K
  

288

In [71]:
ds = xr.open_dataset('/data/ycheng/JRA/Data/1971/hgt_19710101.nc')

In [74]:
ds2 = xr.open_dataset('/data/ycheng/JRA/Data/1970/hgt_1970.nc')

In [75]:
ds['longitude']

<xarray.DataArray 'longitude' (longitude: 144)>
array([ -2.5,   0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,
        22.5,  25. ,  27.5,  30. ,  32.5,  35. ,  37.5,  40. ,  42.5,  45. ,
        47.5,  50. ,  52.5,  55. ,  57.5,  60. ,  62.5,  65. ,  67.5,  70. ,
        72.5,  75. ,  77.5,  80. ,  82.5,  85. ,  87.5,  90. ,  92.5,  95. ,
        97.5, 100. , 102.5, 105. , 107.5, 110. , 112.5, 115. , 117.5, 120. ,
       122.5, 125. , 127.5, 130. , 132.5, 135. , 137.5, 140. , 142.5, 145. ,
       147.5, 150. , 152.5, 155. , 157.5, 160. , 162.5, 165. , 167.5, 170. ,
       172.5, 175. , 177.5, 180. , 182.5, 185. , 187.5, 190. , 192.5, 195. ,
       197.5, 200. , 202.5, 205. , 207.5, 210. , 212.5, 215. , 217.5, 220. ,
       222.5, 225. , 227.5, 230. , 232.5, 235. , 237.5, 240. , 242.5, 245. ,
       247.5, 250. , 252.5, 255. , 257.5, 260. , 262.5, 265. , 267.5, 270. ,
       272.5, 275. , 277.5, 280. , 282.5, 285. , 287.5, 290. , 292.5, 295. ,
       297.5, 300. , 302.5, 305. , 307.5, 310. , 312.5, 315. , 317.5, 320. ,
       322.5, 325. , 327.5, 330. , 332.5, 335. , 337.5, 340. , 342.5, 345. ,
       347.5, 350. , 352.5, 355. ])
Coordinates:
    number     int64 ...
    step       timedelta64[ns] ...
  * longitude  (longitude) float64 -2.5 0.0 2.5 5.0 ... 347.5 350.0 352.5 355.0
Attributes:
    units:          degrees_east
    standard_name:  longitude
    long_name:      longitude

In [76]:
ds2['longitude']

<xarray.DataArray 'longitude' (longitude: 144)>
array([  0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,  22.5,
        25. ,  27.5,  30. ,  32.5,  35. ,  37.5,  40. ,  42.5,  45. ,  47.5,
        50. ,  52.5,  55. ,  57.5,  60. ,  62.5,  65. ,  67.5,  70. ,  72.5,
        75. ,  77.5,  80. ,  82.5,  85. ,  87.5,  90. ,  92.5,  95. ,  97.5,
       100. , 102.5, 105. , 107.5, 110. , 112.5, 115. , 117.5, 120. , 122.5,
       125. , 127.5, 130. , 132.5, 135. , 137.5, 140. , 142.5, 145. , 147.5,
       150. , 152.5, 155. , 157.5, 160. , 162.5, 165. , 167.5, 170. , 172.5,
       175. , 177.5, 180. , 182.5, 185. , 187.5, 190. , 192.5, 195. , 197.5,
       200. , 202.5, 205. , 207.5, 210. , 212.5, 215. , 217.5, 220. , 222.5,
       225. , 227.5, 230. , 232.5, 235. , 237.5, 240. , 242.5, 245. , 247.5,
       250. , 252.5, 255. , 257.5, 260. , 262.5, 265. , 267.5, 270. , 272.5,
       275. , 277.5, 280. , 282.5, 285. , 287.5, 290. , 292.5, 295. , 297.5,
       300. , 302.5, 305. , 307.5, 310. , 312.5, 315. , 317.5, 320. , 322.5,
       325. , 327.5, 330. , 332.5, 335. , 337.5, 340. , 342.5, 345. , 347.5,
       350. , 352.5, 355. , 357.5])
Coordinates:
    number     int64 ...
    step       timedelta64[ns] ...
  * longitude  (longitude) float64 0.0 2.5 5.0 7.5 ... 350.0 352.5 355.0 357.5