In [2]:
import numpy as np
from datetime import datetime as dt,timedelta
import xarray as xr
import importlib
from lib import driver
 #import the module here, so that it can be reloaded.
importlib.reload(driver)
from lib import dataset
import netCDF4 as nc
import matplotlib.pyplot as plt
from lib.tools import *
from cartopy import crs as ccrs
from datetime import datetime as dt,timedelta
from calendar import monthrange
import scipy as scipy
from scipy import signal as sig, linalg, stats




In [2]:
expt_name = 'realtime'
LIMdriver = driver.Driver(f'namelist_{expt_name}.py')
LIMdriver.get_variables()
LIMdriver.get_eofs()
LIMdriver.prep_realtime_data(limkey=1,use_sliding_climo_realtime=True, verbose=True) 


reading  data_clim/tmp/fullyr_JRA_58-16_sliding_climo_SST.p
reading  data_clim/tmp/fullyr_JRA_58-16_sliding_climo_SF750.p
reading  data_clim/tmp/fullyr_JRA_58-16_sliding_climo_SF100.p
reading  data_clim/tmp/fullyr_JRA_58-16_sliding_climo_T2m.p
reading  data_clim/tmp/fullyr_JRA_58-16_sliding_climo_SLP.p
reading  data_clim/tmp/fullyr_JRA_58-16_sliding_climo_H500.p
reading  data_clim/tmp/fullyr_JRA_58-16_sliding_climo_colIrr.p
reading  data_clim/tmp/fullyr_JRA_58-16_sliding_climo_SOIL.p
reading colIrr for LIM 1
reading H500 for LIM 1
reading SLP for LIM 1
reading T2m for LIM 1
reading SOIL for LIM 1
reading SF750 for LIM 1
reading SF100 for LIM 1
reading SST for LIM 1
reading CPCtemp for LIM 1
reading colIrr for LIM 2
reading H500 for LIM 2
reading SLP for LIM 2
reading T2m for LIM 2
reading SOIL for LIM 2
reading SF750 for LIM 2
reading SF100 for LIM 2
reading SST for LIM 2
reading CPCtemp for LIM 2
reading colIrr for LIM 3
reading H500 for LIM 3
reading SLP for LIM 3
reading T2m for LIM

In [3]:
FORECASTDAYS = dt(2023,6,14)
T_INIT = FORECASTDAYS
weekday = T_INIT.weekday()
dayoffset = (4-weekday)%7


pc_convert = None
# pc_convert = ['T2m','CPCtempHR']

# Run the LIM forecast
LIMdriver.run_forecast_blend(t_init=T_INIT,lead_times=np.arange(0,3),fullVariance=True,\
            pc_convert=pc_convert) # Save files using LIMdriver.save_netcdf_files               


[datetime.datetime(2023, 6, 14, 0, 0)]
!!!!
--> Performing LIM forecast for lead times: [0 1 2]
Got Forecast From LIM 5


/home/ycheng/.conda/envs/cpc/lib/python3.10/site-packages/numpy/lib/nanfunctions.py:1872: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/ycheng/LIM/v2_CPC/run_code/lib/dataset.py:694: RuntimeWarning: invalid value encountered in sqrt
  recon = np.array([np.diag(np.matrix(self.eof).T[:,:num_eofs] @ p \


--> Performing LIM forecast for lead times: [0 1 2]
Got Forecast From LIM 6
--> Performing LIM forecast for lead times: [0 1 2]
Got Forecast From LIM 7


In [7]:
LIMdriver.run_forecast(t_init=T_INIT,lead_times=np.arange(0,3),fullVariance=True) # Save files using LIMdriver.save_netcdf_files  

--> Performing LIM forecast for lead times: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


In [13]:
t_init = dt(2023,9,25)
days_in_month = max(monthrange(t_init.year,t_init.month))

mn1=8
mn2=9
mn3=10
weights = {mn1:1-min([t_init.day,7])/7,mn2:1,mn3:1-min([days_in_month-t_init.day,7])/7}
print(f'weights = {weights}')

weights = {8: 0.0, 9: 1, 10: 0.2857142857142857}


In [14]:
# 2D arrays (matrices)
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Dot product of 2D arrays
result_matrix = np.dot(matrix_a, matrix_b)
print("Dot product of matrix_a and matrix_b:\n", result_matrix)


Dot product of matrix_a and matrix_b:
 [[19 22]
 [43 50]]


In [15]:
print(matrix_a)

[[1 2]
 [3 4]]


In [6]:
np.product(np.array([5,2]))

10

In [7]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))  # Matrix multiplication
print(A@B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [14]:
Pshape = A.shape
Pshape=(5,2)
print(type(Pshape))
np.product(Pshape[:-1])

<class 'tuple'>


5

In [18]:
t0=dt.now().replace(hour=0,minute=0,second=0,microsecond=0)
print([t0+timedelta(days=i-120) for i in range(120)])

[datetime.datetime(2023, 5, 25, 0, 0), datetime.datetime(2023, 5, 26, 0, 0), datetime.datetime(2023, 5, 27, 0, 0), datetime.datetime(2023, 5, 28, 0, 0), datetime.datetime(2023, 5, 29, 0, 0), datetime.datetime(2023, 5, 30, 0, 0), datetime.datetime(2023, 5, 31, 0, 0), datetime.datetime(2023, 6, 1, 0, 0), datetime.datetime(2023, 6, 2, 0, 0), datetime.datetime(2023, 6, 3, 0, 0), datetime.datetime(2023, 6, 4, 0, 0), datetime.datetime(2023, 6, 5, 0, 0), datetime.datetime(2023, 6, 6, 0, 0), datetime.datetime(2023, 6, 7, 0, 0), datetime.datetime(2023, 6, 8, 0, 0), datetime.datetime(2023, 6, 9, 0, 0), datetime.datetime(2023, 6, 10, 0, 0), datetime.datetime(2023, 6, 11, 0, 0), datetime.datetime(2023, 6, 12, 0, 0), datetime.datetime(2023, 6, 13, 0, 0), datetime.datetime(2023, 6, 14, 0, 0), datetime.datetime(2023, 6, 15, 0, 0), datetime.datetime(2023, 6, 16, 0, 0), datetime.datetime(2023, 6, 17, 0, 0), datetime.datetime(2023, 6, 18, 0, 0), datetime.datetime(2023, 6, 19, 0, 0), datetime.datetime(20

In [19]:
dic = {"a":1, "b": np.array([1,2])}
print(len(dic))

2


In [20]:
print(type(dic))

<class 'dict'>


In [21]:
import numpy as np

data = np.array([1, 2, np.nan, 4, 5])
std = np.std(data)
print("Standard deviation (including NaN):", std)  # Output: nan
print(np.nanstd(data))

Standard deviation (including NaN): nan
1.5811388300841898


In [8]:

# Example 2D array
fcst = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]]

print("Original array:")
print(np.array(fcst))
# Convert to NumPy array and swap axes
fcst = np.array(fcst).swapaxes(0, 1)



print("\nArray after swapping axes:")
print(fcst)


Original array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Array after swapping axes:
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [27]:
fcst = [-1,1]
spread = [1,1]
fnorm = [stats.norm(loc = np.array(f),scale = np.array(s)) for f,s in zip(fcst,spread)]

In [28]:
bounds = [-np.inf*np.ones(1)]+[np.zeros(1)]+[np.inf*np.ones(1)]
# bounds = [-2.35]+[np.zeros(1)]+[np.inf*np.ones(1)]
K = len(bounds)-1
cat_fcst = [np.array([f.cdf(bounds[c+1])-f.cdf(bounds[c]) for c in range(K)]).squeeze() for f in fnorm]


In [29]:
print(cat_fcst)

[array([0.84134475, 0.15865525]), array([0.15865525, 0.84134475])]


In [14]:
for i in range(2,10,1):
    T_INIT = dt(2023,10,i)
    weekday = T_INIT.weekday()
    dayoffset = (4-weekday)%7
    print(f'weekday = {T_INIT.weekday()}; {T_INIT} = {dayoffset}')

weekday = 0; 2023-10-02 00:00:00 = 4
weekday = 1; 2023-10-03 00:00:00 = 3
weekday = 2; 2023-10-04 00:00:00 = 2
weekday = 3; 2023-10-05 00:00:00 = 1
weekday = 4; 2023-10-06 00:00:00 = 0
weekday = 5; 2023-10-07 00:00:00 = 6
weekday = 6; 2023-10-08 00:00:00 = 5
weekday = 0; 2023-10-09 00:00:00 = 4


5
