In [1]:
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime as dt,timedelta


In [3]:
# Sample time values
RT_VARS_time = [1, 2, 3, 4, 5]

# Sample values for variable 'name'
RT_PCS_name = [10, 20, 30, 40, 50]

# Sample 'init_times' list
init_times = [2, 4, 6]

# Using the generator expression with 'zip'
result = [(t, p) for t, p in zip(RT_VARS_time, RT_PCS_name) if t in init_times]

print(result)



[(2, 20), (4, 40)]


In [5]:
list_of_p = []
for t, p in zip(RT_VARS_time, RT_PCS_name):
    if t in init_times:
        list_of_p.append(p)

In [6]:
print(list_of_p)

[20, 40]


In [33]:
import numpy as np
import numpy as np

# Sample array of shape (6, 87)
# original_array = np.random.rand(6, 87)
original_array = np.random.rand(4,6,87)

# Columns to exclude (indices to mask out)
columns_to_retain = np.arange(2,5)
mask = np.zeros((1, original_array.shape[2]), dtype=bool)
mask[0, columns_to_retain] = True
masked_array = original_array * mask
print(mask.shape)
print("Original Array:")
print(original_array)

print("\nMasked Array (Excluding columns 1, 3, and 5):")
print(masked_array)


(1, 87)
Original Array:
[[[0.35574537 0.63562358 0.40718576 ... 0.02375912 0.70294386 0.35722787]
  [0.97392739 0.9781372  0.34668684 ... 0.98679172 0.26418374 0.29931024]
  [0.8322333  0.9528467  0.19735012 ... 0.17022573 0.79347681 0.43356934]
  [0.31951814 0.7876469  0.47455142 ... 0.06723113 0.98922398 0.90139229]
  [0.68707875 0.82473219 0.74571329 ... 0.71111955 0.56819384 0.91163853]
  [0.56204505 0.4046207  0.38893689 ... 0.46526051 0.79994802 0.99204675]]

 [[0.67851282 0.36899206 0.68236429 ... 0.56938281 0.87998782 0.7259836 ]
  [0.77128753 0.76882538 0.03569088 ... 0.53779535 0.32996706 0.70858666]
  [0.72844466 0.25731371 0.11444156 ... 0.21458898 0.97830898 0.44496076]
  [0.16817229 0.25539013 0.22716695 ... 0.69060125 0.15819417 0.74448203]
  [0.25485955 0.20896344 0.99841387 ... 0.93140688 0.37762456 0.23475418]
  [0.46872226 0.69734655 0.35953704 ... 0.75801226 0.74267078 0.75191333]]

 [[0.66516418 0.23122874 0.61357923 ... 0.18756203 0.32955917 0.23171034]
  [0.29423

In [28]:
npcs = [23,8,20,7,5,8,8,8]
colStart = 0
colEnd   = 0
for npc in npcs:
    colEnd   = colStart + npc-1
    print(npc, colStart, colEnd)
        colStart = colEnd + 1


23 0 22
8 23 30
20 31 50
7 51 57
5 58 62
8 63 70
8 71 78
8 79 86
