In [2]:
import numpy as np

In [1]:
var_choice = 'Sam_vars'
forecast_mode = 'reforecast'
# forecast_mode = 'hindcast_fold10'
forecast_mode = 'hindcast_fold9'
expt_name = f'12_{var_choice}_{forecast_mode}'

training_periods = {
"reforecast"     : {"period1": (1958,2016)},
"hindcast_fold10": {"period1": (1958,2010)},
"hindcast_fold9" : {"period1": (1958,2004), "period2":(2011,2016)},
                               
}

in_data_folder = "/Projects/jalbers_process/CPC_LIM/yuan_ming/Data/9b2_sliding_climo_no_double_running_mean"
out_data_folder = f"/Projects/jalbers_process/CPC_LIM/yuan_ming/Data/{expt_name}"

if var_choice == '8_vars':
    varnames = ["T2m", "SOIL", "SLP", "colIrr", "H500", "SST", "SF100", "SF750"]
elif var_choice == 'Sam_vars':
    varnames = ["T2m", "SLP", "colIrr", "H500", "SF100"]

for period, years in training_periods[forecast_mode].items():
    start_year, end_year = years
    print(varnames) 
    print(period,f'{start_year} -- {end_year}')  

['T2m', 'SLP', 'colIrr', 'H500', 'SF100']
period1 1958 -- 2004
['T2m', 'SLP', 'colIrr', 'H500', 'SF100']
period2 2011 -- 2016


In [5]:
np.linspace(-10,10,21).astype(int)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [6]:
np.array(-5,-4,-3,-1)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [8]:
np.array([-5,-4,-3,-2,-1,]).astype(int)

array([ 5, -4, -3, -1])

In [11]:
prop={}
prop['cmap'] = {0:'violet',22.5:'mediumblue',40:'lightskyblue',\
                47.5:'w',52.5:'w',60:'gold',77.5:'firebrick',100:'violet'}
len(prop['levels'])

KeyError: 'levels'

In [12]:
np.linspace(-6,6,13)

array([-6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.])